### PR TITLE
Added right-alt keycode

### PR DESCRIPTION
**Pull request by benjaminaigner**
Added the right-alt keycode, which is supported by FABI & FM.
Keycode is according to https://keycode.info
@klues I hope that's the right way :-)

### CODE REVIEW

**Comment by klues** [comment]
Is `Right-Alt` the same as `Alt Gr`? Because on my environment `Alt Gr` is javascript keycode `18` and I don't have any other Alt-key that has keycode `255` - see https://i.imgur.com/Ja30MRj.png. Beside of this it should be the right way, have you tested if your changes result in having `Alt-Right` available to select in the GUI?

**Comment by benjaminaigner** [comment]
Interesting... I have 225 for RightAlt :-).
And it is necessary to type e.g. {[]} on a German keyboard layout.

Is it possible for you to type in "{" by using the left Alt + Ctrl + 7?

This modification works on my Linux machine (detecting right alt in the GUI and typing in {[]}).

Screenshot from 2021-11-30 09-53-11

**Comment by klues** [comment]
Interesting...
For me it's all the same, but only the AltRight keycode is `18`...
Alt + Ctrl + 7 also prints `{` for me.

**Comment by benjaminaigner** [comment]
OK, on my keyboard i cannot type {[]} without the right alt.
Then it should not make any difference for Win Users,
either way the correct Alt Key for the current layout should be detected.

**Comment by klues** [comment]
As far as I know the javascript keycode is only to necessary to write the correct FM/FABI-keycodes here when typing via keyboard: https://i.imgur.com/EsELQjb.png

On Windows it detects `Alt Gr` as `Ctrl + Alt`, so I think it's fine to just add the `Right Alt` as you did, which then should be detected on Linux machines (and also can be added manually via the dropbox above on Windows).
So if it works as expected on your machine, just merge :)

**Pull request merged**
